### ISSUE TITLE
how to use?

### ISSUE THREAD

**Issue by flyerhzm** [psequel/psequel-issues#2]
When I open psequel, I just saw a window, just text "Connections" at left sidebar, nothing I can click or view. I guess it's connection issue (I always use postgres user on psql).

**Comment by ngocphamm** [comment]
Just realized I need to create a new connection with the "+" icon in order to connect to a database. If just entering information on the right hand side inputs, it does not work at all, with no message. I wish it would be more obvious.

**Comment by psequel** [comment]
In earlier versions, the right hand side panel will be hidden if no connection has been created. In the latest version, in order to support SSH tunneling, I redesigned the whole right panel and forgot to make it hidden for empty connections. This bug will be fixed in the next release. Sorry for the confusion.

**Comment by ngocphamm** [comment]
No problem. Thank you for quick follow up. Also thanks for a nice app. It's really getting to the point in which it should be, IMO.

**Comment by nitsujri** [comment]
+1 For this, just downloaded and was thoroughly confused at the connect button doing nothing/response.

Thanks for everything you do!

**Comment by jjulian** [comment]
I was also confused. Maybe the fields should be un-editable (or hidden) until `+` is clicked?

**Comment by psequel** [comment]
Fixed in v1.0.9.
