### ISSUE TITLE
Support for Redshift

### ISSUE THREAD

**Issue by john-sandall** [psequel/psequel-issues#25]
As mentioned by a couple people on Hacker News, would love proper support for Redshift. Specifically, displaying tables and metadata for PostgreSQL 8.3 and earlier.

Currently displays error message `"column "typcategory" does not exist"` on load.

**Comment by gregoryb** [comment]
+1 for Redshift ;)

**Comment by psylum** [comment]
+1 for Redshift as well. Even if only as far as listing tables so it's easier to work on raw queries.

**Comment by ofirbb** [comment]
+1 for Redshift

**Comment by whootang12** [comment]
+1 as well

**Comment by psequel** [comment]
I will start working on Redshift support next month.

**Comment by spencersmith** [comment]
Any update on this? I would LOVE to have support for redshift.

**Comment by mrn3** [comment]
+1 for this - what are the challenges with this?  Is it integrating the redshift driver?  I assume you can just connect to Redshift just like any other postgres database, so not sure why it doesn't work currently (using the postgres driver).  Perhaps there are other issues because Redshift doesn't support all the same types and such as postgres.

**Comment by spencersmith** [comment]
@mrn3 I'm not sure what the differences would be, however I do know redshift was forked off postgres 8.4. I'm sure there are a pretty decent amount of differences by this point.

**Comment by mrn3** [comment]
I see - that makes sense.  I actually connected to a redshift instance and it kind of connects and I was able to see some schema info, but no data (it was throwing errors).  So, I assume the errors are just related to the forking and versioning mismatches.

**Comment by psequel** [comment]
@spencersmith [Redshift was was forked off postgres 8.0.2](http://docs.aws.amazon.com/redshift/latest/dg/c_redshift-and-postgres-sql.html), not 8.4.

**Comment by spencersmith** [comment]
Ah my apologies! I'm sure that makes my point even more drastic then. 



—

**Comment by Koff** [comment]
+1 For RedShift support, even if only removing the continuous error that appears every time a switch in schema happens.

**Comment by psequel** [comment]
[V1.2.1.beta](http://www.psequel.com/download?version=1.2.1.beta) has preliminary support for Redshift.

**Comment by spencersmith** [comment]
Looks pretty good at first glance! :+1:

**Comment by Koff** [comment]
Awesome work!

Thanks :-)

**Comment by mlaprise** [comment]
Hey thx for this v1.2.1beta. I just tested it on our Redshift data warehouse and  I don't have the error message anymore ! However, when I click on my table in the UI, a query like this is sent

SELECT "field1", "field2"
FROM my_table
ORDER BY "my_timestamp_field"
LIMIT 25

without any predicate on the sort key which obviously takes forever since we effectively sorting the entire table. Could we simply remove the ORDER BY clause ?

**Comment by psequel** [comment]
@mlaprise Without the ORDER BY clause, the returned result will be unpredictable, and the pagination will look wonky. See http://stackoverflow.com/q/10064532. By default, PSequel uses primary keys in the ORDER BY clause, which shouldn't take that long on sorting.

**Comment by psequel** [comment]
@mlaprise In the latest beta release, you could disable "ordering by primary keys by default" in Preferences.
