### ISSUE TITLE
Buttons are inaccessible on popup

### ISSUE THREAD

**Issue by matthew-dean** [psequel/psequel-issues#29]
With large fields or large numbers of fields, the buttons on the popup form become inaccessible. 

![screen shot 2015-03-04 at 9 19 13 am](https://cloud.githubusercontent.com/assets/414752/6489027/1f4f35cc-c250-11e4-903b-76e21ddc0ddf.png)

**Comment by bawigga** [comment]
I'm able to scroll down to get to the buttons. Maybe make sure your mouse focus is in the grey margins?

**Comment by matthew-dean** [comment]
Oh. Well, that works but it's not intuitive. Ok / Cancel buttons should not be part of a scrollable window by convention. The popup should be a comfortable max-height with the fields in a scrollable area.

**Comment by bawigga** [comment]
@matthew-dean  +1 to that

**Comment by psequel** [comment]
If I move the buttons outside the scrollable area, still some people may think the text fields area gets clipped and may not realize that it's scrollable.

The problem is that, in Yosemite, scroll bars are hidden by default (you can change this in System Preference). For instance, in your web browser, you don't know whether or not a web page is scrollable until you try to scroll it. It's not very intuitive at the beginning, but you will get used to it.
