### ISSUE TITLE
Large table causes Crash

### ISSUE THREAD

**Issue by daneb** [psequel/psequel-issues#32]
Good day

How:
By simply clicking on the name of the table and allowing it time to load. The error/ crash usually happens in a matter of seconds.

When:
When opening a large table the application crashes.
Best estimate of size is about 5 million rows over a network.

Upon request I can paste the entire error message.

Output:
Process:               PSequel [2631]
Path:                  /Applications/PSequel.app/Contents/MacOS/PSequel
Identifier:            com.psequel.PSequel
Version:               1 (1.1.0)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           PSequel [2631]
User ID:               501

Date/Time:             2015-03-30 08:01:04.336 +0200
OS Version:            Mac OS X 10.10.2 (14C1514)
Report Version:        11
Anonymous UUID:        04E1D4DA-CD1F-0CEB-B43B-0E08900B3DAE

Sleep/Wake UUID:       ADBB93AC-FC35-4220-AB52-C9493891BA29

Time Awake Since Boot: 3400 seconds
Time Since Wake:       2600 seconds

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000002, 0x0000000000000000

**Comment by psequel** [comment]
Could you try this: click on a small table first, change page size to something other than "unlimited", and then click on the large table? Does this solve the issue? Some people suggested me to remove the "unlimited" option.

**Comment by scttcper** [comment]
I'm running into the same problem. Limiting the page size before changing tables does not fix the issue. If you'd like to connect to the database I'm using we could arrange that. It's a side project with no personal data.


Process:               PSequel [8564]
Path:                  /Applications/PSequel.app/Contents/MacOS/PSequel
Identifier:            com.psequel.PSequel
Version:               1 (1.1.0)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           PSequel [8564]
User ID:               501

Date/Time:             2015-04-01 13:34:29.033 -0700
OS Version:            Mac OS X 10.10.2 (14C1514)
Report Version:        11
Anonymous UUID:        57617645-5C47-33D0-2A69-072006A64E0D

Sleep/Wake UUID:       3F2046E9-A2DA-45CA-BF5C-E1F57038EE67

Time Awake Since Boot: 340000 seconds
Time Since Wake:       10000 seconds

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000002, 0x0000000000000000

**Comment by psequel** [comment]
I just checked. The app is able to display data of a local database table with 1M rows and 50 varchar(255) columns - page size set to 1000. How many rows/columns in your table? Are there some of fields have a huge size of data? Send the connection details of your db to support (at) psequel (dot) com if you want.

**Comment by scttcper** [comment]
The smaller table that crashes has 2782146 rows. The bigger one has 27536595.

Smaller "match" table has rows that look like this
117532798,"0.0.0.0","caldavar",1044,"2013-06-15 02:00:09",1

```
hb=# \d match
                                    Table "public.match"
  Column  |            Type             |                     Modifiers                      
----------+-----------------------------+----------------------------------------------------
 id       | integer                     | not null default nextval('match_id_seq'::regclass)
 version  | character varying(10)       | 
 map_used | character varying(20)       | 
 length   | integer                     | 
 date     | timestamp without time zone | 
 mode     | integer                     | 
Indexes:
    "match_pkey" PRIMARY KEY, btree (id)
    "ix_match_map_used" btree (map_used)
    "ix_match_mode" btree (mode)
    "ix_match_version" btree (version)
Referenced by:
    TABLE "playermatch" CONSTRAINT "playermatch_match_id_fkey" FOREIGN KEY (match_id) REFERENCES match(id)
```

I'll send you an email in a minute.

**Comment by psequel** [comment]
V1.1.1 should fix this issue. There was a bug in converting postgres data types to Swift native data types for certain database tables. It was not because of the table size.

**Comment by scttcper** [comment]
Wow that was quick, it's fixed for me! :+1:

**Comment by daneb** [comment]
Wow, great turnaround time!
Thank you, that worked the charm and sorry for MY delayed response.
